import json

with open("src/data/platforms.json", "r") as f:
    platforms = json.load(f)

idx = {p["id"]: i for i, p in enumerate(platforms)}

updates = {
    "amazon-flex": {"estimatedHourlyMin":18,"estimatedHourlyMax":25,"keyFeatures":"Pre-booking blocks; guaranteed earnings visibility before committing.","userFeedback":"Pros: Earnings transparency. Cons: High competition makes it difficult to secure blocks.","lastUpdated":"2026-02-27"},
    "curri": {"estimatedHourlyMin":10,"estimatedHourlyMax":50,"instantPayAvailable":True,"keyFeatures":"Bidding system for carriers; upfront pay transparency; route navigation; fuel discount program access. Instant Pay available (1% fee).","userFeedback":"3.0 out of 5; Favored by owners of larger vehicles; better pay than food delivery; noted long approval wait times and unhelpful support.","lastUpdated":"2026-02-27"},
    "deliverthat": {"estimatedHourlyMin":15,"estimatedHourlyMax":40,"keyFeatures":"Pre-booking orders (day before); 100% tip retention; tiered driver levels.","userFeedback":"3.3 out of 5 (Indeed); Keeps drivers busy; requires upfront payment for bags/MVR.","lastUpdated":"2026-02-27"},
    "doordash": {"estimatedHourlyMin":15,"estimatedHourlyMax":25,"keyFeatures":"Shop and deliver option; alcohol delivery; toggle filters.","userFeedback":"Pros: Simple and easy. Cons: Market saturation in small towns.","lastUpdated":"2026-02-27"},
    "expedite": {"estimatedHourlyMin":40,"estimatedHourlyMax":50,"instantPayAvailable":True,"keyFeatures":"Emerald Elite tiers; corporate tip transparency; stacking orders; catering bag requirement tracking. Same-day pay via Everee.","userFeedback":"2.3 to 3.3 out of 5; Highly favorable for per-order earnings; some complaints about low order frequency and app notification issues.","description":"dlivrd (formerly Expedite) is a catering delivery and specialty logistics platform operating in 180 markets across the U.S. and Canada. Drivers earn $20-$60 per order with an average of $40-$50/hr. Features Emerald Elite tiers, corporate tip transparency, and the ability to stack orders. Same-day pay available via Everee.","lastUpdated":"2026-02-27"},
    "frayt": {"estimatedHourlyMin":20,"estimatedHourlyMax":30,"instantPayAvailable":True,"keyFeatures":"Preferred Driver Program; Branch app integration; stacked offers (up to 3); 24/7 support; box truck options. Daily payouts available.","userFeedback":"4.3 to 4.8 out of 5; Positive for local runs and communication; frustration over $40 non-refundable application fee and glitchy app.","lastUpdated":"2026-02-27"},
    "goshare": {"estimatedHourlyMin":40,"estimatedHourlyMax":168,"keyFeatures":"Load board notifications; proof of delivery tools; healthcare discounts; last mile delivery. Earnings depend on vehicle type.","userFeedback":"4.7 out of 5 (12K ratings); High earnings for large vehicles; some reports of project requests not appearing; requires DOT number for sign-up.","lastUpdated":"2026-02-27"},
    "grubhub": {"estimatedHourlyMin":18,"estimatedHourlyMax":19,"keyFeatures":"Food delivery with higher tip-to-base pay ratio (2:1 average).","userFeedback":"Pros: Higher tip-to-base pay ratio (2:1). Cons: Lower order volume compared to competitors.","lastUpdated":"2026-02-27"},
    "instacart": {"estimatedHourlyMin":18,"estimatedHourlyMax":19,"keyFeatures":"Grocery shop and delivery; batch orders.","userFeedback":"Pros: Good for those who prefer shopping. Cons: Honeymoon period for new hires followed by lower pay.","lastUpdated":"2026-02-27"},
    "lyft": {"estimatedHourlyMin":15,"estimatedHourlyMax":33,"instantPayAvailable":True,"keyFeatures":"Turbo earnings (10-40% more); Ride Challenges; Bonus Zones; Express Drive (car rental); Express Pay daily for fee; Lyft Direct instant pay.","userFeedback":"Positive for bonus opportunities; keep 100% of tips; earnings vary heavily by location and timing.","lastUpdated":"2026-02-27"},
    "roadie": {"estimatedHourlyMin":20,"estimatedHourlyMax":20,"keyFeatures":"Owned by UPS; map-based offer selection; diverse items (luggage to furniture).","userFeedback":"Pros: Visual map for jobs. Cons: High mileage required for low-paying deliveries (e.g., CVS).","lastUpdated":"2026-02-27"},
    "senpex": {"estimatedHourlyMin":96,"estimatedHourlyMax":142,"keyFeatures":"White-glove handling; catering setup; real-time tracking; route management; 85-90% commission.","userFeedback":"3.4 to 3.9 out of 5; Pros: High commission and fast feedback; Cons: Poor driver support, app glitches, and disappearing orders.","lastUpdated":"2026-02-27"},
    "shipt": {"estimatedHourlyMin":20,"estimatedHourlyMax":33,"keyFeatures":"Target-owned shopping app; shop and deliver.","userFeedback":"Pros: High peak holiday earnings. Cons: High variability by location.","lastUpdated":"2026-02-27"},
    "spark-driver": {"estimatedHourlyMin":15,"estimatedHourlyMax":24,"keyFeatures":"Walmart delivery; return orders; cellular discounts; incentives program.","userFeedback":"Pros: Reward programs. Cons: Batch orders often contain heavy items.","lastUpdated":"2026-02-27"},
    "uber": {"estimatedHourlyMin":15,"estimatedHourlyMax":50,"instantPayAvailable":True,"keyFeatures":"Upfront fares; Uber Pro Card (cash back on gas); toggle between transport and Uber Eats; Instant Pay up to 6x daily for $0.85 fee.","userFeedback":"Variable; High peak earnings but concerns over vehicle maintenance, depreciation, and declining pay rates.","lastUpdated":"2026-02-27"}
}

for pid, fields in updates.items():
    if pid in idx:
        for k, v in fields.items():
            platforms[idx[pid]][k] = v
        print(f"  Updated: {pid}")
    else:
        print(f"  NOT FOUND: {pid}")

new_platforms = [
    {"id":"american-expediting","slug":"american-expediting","name":"American Expediting","description":"American Expediting is a medical and specialized courier service operating nationwide with 50+ locations in the U.S. and Canada. Drivers handle time-sensitive deliveries including medical specimens, legal documents, and other critical materials. The platform offers TSA, HIPAA, and Bloodborne Pathogens certification access, fuel and insurance discounts, and digital management via Openforce.","logoUrl":None,"websiteUrl":"https://www.amexpediting.com","iosAppUrl":None,"androidAppUrl":None,"categories":["medical_courier","specialized_delivery","same_day_delivery"],"minAge":21,"backgroundCheckRequired":True,"vehicleTypes":["car","suv","van"],"licenseRequired":True,"insuranceRequired":True,"equipmentNeeded":["smartphone"],"countries":["USA","Canada"],"regions":{"USA":{"status":"Active","cities":[]},"Canada":{"status":"Active","cities":[]}},"payModel":"hourly","estimatedHourlyMin":16,"estimatedHourlyMax":20,"tipsAllowed":False,"paymentFrequency":"weekly","instantPayAvailable":False,"deliveryType":"on_demand","usesThirdPartyDelivery":False,"driverStatus":"active","lastUpdated":"2026-02-27","dataSources":["official_website","indeed"],"verificationStatus":"verified","setupRequired":True,"keyFeatures":"TSA, HIPAA, and Bloodborne Pathogens certification access; fuel and insurance discounts; digital management via Openforce.","userFeedback":"2.9 out of 5 (Indeed); Professional environment with high reliability expectations; noted significant insurance (100/300) and upfront fees."},
    {"id":"field-agent","slug":"field-agent","name":"Field Agent","description":"Field Agent is a retail audit and mystery shopping platform where gig workers complete in-store tasks like photo audits, price checks, and product displays. No car is required - tasks are accessible via walking or transit. Earn $3 to $20+ per task with an equivalent hourly rate of $28-$30/hr.","logoUrl":None,"websiteUrl":"https://www.fieldagent.net","iosAppUrl":None,"androidAppUrl":None,"categories":["retail_audit","mystery_shopping","task_based"],"minAge":18,"backgroundCheckRequired":False,"vehicleTypes":["none","car","bike"],"licenseRequired":False,"insuranceRequired":False,"equipmentNeeded":["smartphone"],"countries":["USA"],"regions":{"USA":{"status":"Active","cities":[]}},"payModel":"per_task","estimatedHourlyMin":28,"estimatedHourlyMax":30,"tipsAllowed":False,"paymentFrequency":"direct_deposit","instantPayAvailable":False,"deliveryType":"task_based","usesThirdPartyDelivery":False,"driverStatus":"active","lastUpdated":"2026-02-27","dataSources":["official_website"],"verificationStatus":"verified","setupRequired":False,"keyFeatures":"In-store tasks; photo audits; mystery shopping; no car required.","userFeedback":"Pros: Accessible via walking/transit. Cons: Highly competitive; jobs claimed in seconds."},
    {"id":"hyer","slug":"hyer","name":"Hyer","description":"Hyer is an on-demand staffing platform focused on retail merchandising, admin tasks, and general labor. Workers pick up hourly shifts with in-app status updates, a rating system, and Hyer Profiles. Background check costs are covered via earnings. Active in 27 states with heavy concentration in the Midwest.","logoUrl":None,"websiteUrl":"https://www.gethyer.com","iosAppUrl":None,"androidAppUrl":None,"categories":["staffing","retail","admin","general_labor"],"minAge":18,"backgroundCheckRequired":True,"vehicleTypes":["none","car"],"licenseRequired":False,"insuranceRequired":False,"equipmentNeeded":["smartphone"],"countries":["USA"],"regions":{"USA":{"status":"Active","cities":["Detroit","Chicago","Columbus","Philadelphia","Indianapolis"]}},"payModel":"hourly","estimatedHourlyMin":15,"estimatedHourlyMax":25,"tipsAllowed":False,"paymentFrequency":"weekly","instantPayAvailable":True,"deliveryType":"task_based","usesThirdPartyDelivery":False,"driverStatus":"active","lastUpdated":"2026-02-27","dataSources":["official_website","app_store"],"verificationStatus":"verified","setupRequired":False,"keyFeatures":"In-app status updates; rating system; Hyer Profiles; messaging system; background check cost covered via earnings.","userFeedback":"4.7 out of 5 (App Store); Good for retail flexibility; noted long background check times and limited assignments in some areas."},
    {"id":"instawork","slug":"instawork","name":"Instawork","description":"Instawork is a staffing platform for general labor and hospitality shifts offering a hybrid 1099 and W-2 model. Workers get transparent hourly rates, full 8-hour blocks, and a Reliability score tracking system. Active in 40+ major U.S. markets. Instapay lets you access 60% of earnings within 1 hour for a 5% fee.","logoUrl":None,"websiteUrl":"https://www.instawork.com","iosAppUrl":None,"androidAppUrl":None,"categories":["staffing","hospitality","general_labor","warehouse"],"minAge":18,"backgroundCheckRequired":True,"vehicleTypes":["none","car"],"licenseRequired":False,"insuranceRequired":False,"equipmentNeeded":["smartphone"],"countries":["USA"],"regions":{"USA":{"status":"Active","cities":["Chicago","Detroit","Riverside","Los Angeles","Dallas"]}},"payModel":"hourly","estimatedHourlyMin":16,"estimatedHourlyMax":30,"tipsAllowed":False,"paymentFrequency":"weekly","instantPayAvailable":True,"deliveryType":"shift_based","usesThirdPartyDelivery":False,"driverStatus":"active","lastUpdated":"2026-02-27","dataSources":["official_website"],"verificationStatus":"verified","setupRequired":False,"keyFeatures":"Hybrid 1099 and W-2 model; Reliability score tracking; rigorous vetting; full 8-hour blocks; Instapay (60% of earnings in 1 hour for 5% fee).","userFeedback":"Highly positive; perceived as professional and reliable; Instapay requires 2 completed shifts and a 7-day wait."},
    {"id":"observa","slug":"observa","name":"Observa","description":"Observa is a retail audit platform where gig workers earn $10-$25 per gig completing photo audits, merchandising checks, and product displays in stores. Jobs can be reserved for up to 2 hours and payment is sent instantly via PayPal after approval.","logoUrl":None,"websiteUrl":"https://www.observanow.com","iosAppUrl":None,"androidAppUrl":None,"categories":["retail_audit","merchandising","task_based"],"minAge":18,"backgroundCheckRequired":False,"vehicleTypes":["none","car","bike"],"licenseRequired":False,"insuranceRequired":False,"equipmentNeeded":["smartphone"],"countries":["USA"],"regions":{"USA":{"status":"Active","cities":[]}},"payModel":"per_task","estimatedHourlyMin":10,"estimatedHourlyMax":25,"tipsAllowed":False,"paymentFrequency":"instant","instantPayAvailable":True,"deliveryType":"task_based","usesThirdPartyDelivery":False,"driverStatus":"active","lastUpdated":"2026-02-27","dataSources":["official_website"],"verificationStatus":"verified","setupRequired":False,"keyFeatures":"Photo audits; merchandising; 2-hour job reservations; PayPal instant payment.","userFeedback":"Pros: High pay per gig relative to time. Cons: Lower job volume."},
    {"id":"poplin","slug":"poplin","name":"Poplin","description":"Poplin (formerly Laundry Pros) is a specialty home services platform where workers wash, dry, and fold laundry from home. Earn $0.75-$1.50 per pound plus tips, with top earners making up to $6,000/month. Features a ranking system (Bronze/Silver/Gold) and in-app messaging. Active in 500+ cities across the U.S. and Canada.","logoUrl":None,"websiteUrl":"https://www.poplin.co","iosAppUrl":None,"androidAppUrl":None,"categories":["home_services","laundry","work_from_home"],"minAge":18,"backgroundCheckRequired":True,"vehicleTypes":["none","car"],"licenseRequired":False,"insuranceRequired":False,"equipmentNeeded":["smartphone","washer","dryer"],"countries":["USA","Canada"],"regions":{"USA":{"status":"Active","cities":[]},"Canada":{"status":"Active","cities":[]}},"payModel":"per_unit","estimatedHourlyMin":20,"estimatedHourlyMax":40,"tipsAllowed":True,"paymentFrequency":"weekly","instantPayAvailable":False,"deliveryType":"task_based","usesThirdPartyDelivery":False,"driverStatus":"active","lastUpdated":"2026-02-27","dataSources":["official_website"],"verificationStatus":"verified","setupRequired":True,"keyFeatures":"Ranking system (Bronze/Silver/Gold); garment protection plan; detergent choice; in-app messaging; work from home.","userFeedback":"3.3 to 4.4 out of 5; Great for work-from-home roles; community feel; some complaints about app glitches and strict penalties."},
    {"id":"qwick","slug":"qwick","name":"Qwick","description":"Qwick is a hospitality staffing platform connecting workers with shifts at restaurants, hotels, catering companies, and event venues. Offers both 1099 and W-2 options with competitive market-based hourly rates. Features an AI matching assistant (Mara) and Stripe-powered payments. Active in 40+ major U.S. cities.","logoUrl":None,"websiteUrl":"https://www.qwick.com","iosAppUrl":None,"androidAppUrl":None,"categories":["hospitality","staffing","food_service","events"],"minAge":18,"backgroundCheckRequired":True,"vehicleTypes":["none","car"],"licenseRequired":False,"insuranceRequired":False,"equipmentNeeded":["smartphone"],"countries":["USA"],"regions":{"USA":{"status":"Active","cities":["Atlanta","Chicago","Dallas","Miami","New York","Phoenix"]}},"payModel":"hourly","estimatedHourlyMin":18,"estimatedHourlyMax":30,"tipsAllowed":True,"paymentFrequency":"within_48_hours","instantPayAvailable":True,"deliveryType":"shift_based","usesThirdPartyDelivery":False,"driverStatus":"active","lastUpdated":"2026-02-27","dataSources":["official_website"],"verificationStatus":"verified","setupRequired":False,"keyFeatures":"1099 and W-2 options; AI matching assistant (Mara); 1:1 orientation; Stripe-powered payments; Instant Pay (30 mins for 3% fee).","userFeedback":"Very high ratings; respected for high-quality shifts and fast pay; strict no-show policy leads to permanent suspension."},
    {"id":"shiftnow","slug":"shiftnow","name":"shiftNOW","description":"shiftNOW is a hospitality and event staffing platform operating primarily in the Southeast U.S. Workers earn $19-$20/hr on most jobs across 40+ role types. Features a comprehensive profile with video, performance metrics, and Stripe-powered transfers. Pay within 48 hours or Instant Pay (1 hour for 3% fee).","logoUrl":None,"websiteUrl":"https://www.shiftnow.com","iosAppUrl":None,"androidAppUrl":None,"categories":["hospitality","event_staffing","staffing"],"minAge":18,"backgroundCheckRequired":True,"vehicleTypes":["none","car"],"licenseRequired":False,"insuranceRequired":False,"equipmentNeeded":["smartphone"],"countries":["USA"],"regions":{"USA":{"status":"Active","cities":["Charleston","Atlanta","Nashville","Savannah","Memphis"]}},"payModel":"hourly","estimatedHourlyMin":19,"estimatedHourlyMax":20,"tipsAllowed":True,"paymentFrequency":"within_48_hours","instantPayAvailable":True,"deliveryType":"shift_based","usesThirdPartyDelivery":False,"driverStatus":"active","lastUpdated":"2026-02-27","dataSources":["official_website"],"verificationStatus":"verified","setupRequired":False,"keyFeatures":"Comprehensive Shifter profile with video; performance metrics; 40+ role types; Stripe-powered transfers; Instant Pay (1 hour for 3% fee).","userFeedback":"3.5 to 4.6 out of 5; Highly positive for flexibility and quality venues; some reports of technical registration issues."}
]

for pid, fields in updates.items():
    if pid in idx:
        for k, v in fields.items():
            platforms[idx[pid]][k] = v
        print(f"  Updated: {pid}")
    else:
        print(f"  NOT FOUND: {pid}")

for np in new_platforms:
    if np["id"] not in idx:
        platforms.append(np)
        print(f"  Added: {np['name']}")
    else:
        print(f"  Already exists: {np['name']}")

with open("src/data/platforms.json", "w") as f:
    json.dump(platforms, f, indent=2)

print(f"\nDone! Total platforms: {len(platforms)}")
